-- Verificar cobertura de conversaciones para Bugs
SELECT 
    COUNT(DISTINCT C.CAS_CASE_ID) AS TOTAL_CASOS_BUGS,
    COUNT(DISTINCT S.CAS_CASE_ID) AS CASOS_CON_CONVERSACION,
    ROUND(SAFE_DIVIDE(COUNT(DISTINCT S.CAS_CASE_ID), COUNT(DISTINCT C.CAS_CASE_ID)) * 100, 2) AS COBERTURA_PCT
FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
LEFT JOIN `meli-bi-data.WHOWNER.BT_CX_STUDIO_SAMPLE` S 
    ON C.CAS_CASE_ID = S.CAS_CASE_ID
WHERE 1=1
    AND C.SIT_SITE_ID = 'MLB'
    AND C.CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-12-31'
    AND C.PROCESS_NAME LIKE '%Ventas y Publicaciones%'
    AND C.CDU = 'Bugs'
    AND C.PROCESS_BU_CR_REPORTING IN ('ME','ML')
    AND COALESCE(C.FLAG_EXCLUDE_NUMERATOR_CR, 0) = 0
    AND C.SIT_SITE_ID NOT IN ('MLV')
    AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
    AND C.PROCESS_ID NOT IN (1312)
    AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
