-- Deep Dive Reputación ME: Datos consolidados
-- Todas las dimensiones en una sola query

WITH COMMERCE_GROUPS AS (
    SELECT
        CAS_CASE_ID,
        CASE 
            WHEN PROCESS_PROBLEMATIC_REPORTING LIKE '%PDD%' THEN 'PDD'
            WHEN PROCESS_PROBLEMATIC_REPORTING = 'Conflict Others' THEN 'PDD'
            WHEN PROCESS_PROBLEMATIC_REPORTING LIKE '%PNR%' THEN 'PNR'
            WHEN PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
            WHEN PROCESS_PROBLEMATIC_REPORTING LIKE '%Post Compra%' 
                AND PROCESS_GROUP_ECOMMERCE IN ('Comprador') THEN 'PCF_COMPRADOR'
            WHEN PROCESS_PROBLEMATIC_REPORTING LIKE '%Post Compra%' 
                AND PROCESS_GROUP_ECOMMERCE IN ('Vendedor') THEN 'PCF_VENDEDOR'
            WHEN PROCESS_PROBLEMATIC_REPORTING LIKE '%Shipping%' 
                AND PROCESS_GROUP_ECOMMERCE IN ('Comprador') THEN 'ME_PREDESPACHO'
            ELSE 'OTRO'
        END AS AGRUP_COMMERCE
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS`
    WHERE SIT_SITE_ID = 'MLB'
        AND CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-12-31'
),
BASE_FILTERED AS (
    SELECT
        C.CAS_CASE_ID,
        DATE_TRUNC(C.CONTACT_DATE_ID, DAY) as FECHA,
        CASE 
            WHEN C.CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-11-30' THEN 'Nov 2025'
            WHEN C.CONTACT_DATE_ID BETWEEN '2025-12-01' AND '2025-12-31' THEN 'Dec 2025'
        END as PERIODO,
        C.PROCESS_NAME,
        COALESCE(C.CDU, 'Sin CDU') as CDU,
        COALESCE(C.REASON_DETAIL_GROUP_REPORTING, 'Sin Tipificación') as TIPIFICACION,
        COALESCE(C.SOURCE_ID, 'Sin Source') as SOURCE_ID,
        COALESCE(C.SOLUTION_ID, 'Sin Solución') as SOLUTION_ID
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    INNER JOIN COMMERCE_GROUPS CG ON C.CAS_CASE_ID = CG.CAS_CASE_ID
    WHERE C.SIT_SITE_ID = 'MLB'
        AND C.CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-12-31'
        AND C.PROCESS_NAME = 'Reputación ME'
        AND CG.AGRUP_COMMERCE = 'ME_PREDESPACHO'
        AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
        AND C.QUE_QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND C.PROCESS_ID NOT IN (1312)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
)
SELECT
    'TEMPORAL' as TIPO_ANALISIS,
    CAST(FECHA AS STRING) as DIMENSION_VAL,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Nov 2025' THEN CAS_CASE_ID END) as CASOS_NOV,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Dec 2025' THEN CAS_CASE_ID END) as CASOS_DIC
FROM BASE_FILTERED
GROUP BY FECHA

UNION ALL

SELECT
    'CDU' as TIPO_ANALISIS,
    CDU as DIMENSION_VAL,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Nov 2025' THEN CAS_CASE_ID END) as CASOS_NOV,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Dec 2025' THEN CAS_CASE_ID END) as CASOS_DIC
FROM BASE_FILTERED
GROUP BY CDU

UNION ALL

SELECT
    'TIPIFICACION' as TIPO_ANALISIS,
    TIPIFICACION as DIMENSION_VAL,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Nov 2025' THEN CAS_CASE_ID END) as CASOS_NOV,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Dec 2025' THEN CAS_CASE_ID END) as CASOS_DIC
FROM BASE_FILTERED
GROUP BY TIPIFICACION

UNION ALL

SELECT
    'SOURCE_ID' as TIPO_ANALISIS,
    SOURCE_ID as DIMENSION_VAL,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Nov 2025' THEN CAS_CASE_ID END) as CASOS_NOV,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Dec 2025' THEN CAS_CASE_ID END) as CASOS_DIC
FROM BASE_FILTERED
GROUP BY SOURCE_ID

UNION ALL

SELECT
    'SOLUTION_ID' as TIPO_ANALISIS,
    SOLUTION_ID as DIMENSION_VAL,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Nov 2025' THEN CAS_CASE_ID END) as CASOS_NOV,
    COUNT(DISTINCT CASE WHEN PERIODO = 'Dec 2025' THEN CAS_CASE_ID END) as CASOS_DIC
FROM BASE_FILTERED
GROUP BY SOLUTION_ID

ORDER BY TIPO_ANALISIS, (CASOS_DIC - CASOS_NOV) DESC
