-- Deep Dive: Reputación ME - Evolución Temporal
-- Análisis diario Nov-Dic 2025

WITH BASE_FILTERED AS (
    SELECT
        C.CAS_CASE_ID,
        DATE_TRUNC(C.CONTACT_DATE_ID, DAY) as FECHA,
        C.PROCESS_NAME,
        C.CLA_REASON_DETAIL,
        C.SOURCE_ID,
        C.SOLUTION_ID,
        C.CHANNEL_ID
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    WHERE C.SIT_SITE_ID = 'MLB'
        AND C.CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-12-31'
        AND C.PROCESS_NAME = 'Reputación ME'
        AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
        AND C.QUE_QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND C.PROCESS_ID NOT IN (1312)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
)
SELECT
    FECHA,
    COUNT(DISTINCT CAS_CASE_ID) as CASOS,
    COUNT(DISTINCT SOURCE_ID) as CANALES_DISTINTOS,
    COUNT(DISTINCT CLA_REASON_DETAIL) as MOTIVOS_DISTINTOS
FROM BASE_FILTERED
GROUP BY FECHA
ORDER BY FECHA
