-- Ver los CDUs reales disponibles
SELECT 
    C.CDU,
    COUNT(DISTINCT C.CAS_CASE_ID) AS CASOS_NOV,
    COUNT(DISTINCT CASE WHEN C.CONTACT_DATE_ID >= '2025-12-01' THEN C.CAS_CASE_ID END) AS CASOS_DIC
FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
WHERE 1=1
    AND C.SIT_SITE_ID = 'MLB'
    AND C.CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-12-31'
    AND C.PROCESS_NAME = 'Ventas y Publicaciones'
    AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
