-- Identificar el campo correcto para CDU
SELECT 
    CLA_REASON_DETAIL,
    CLA_CDU_L2,
    COUNT(*) AS CASOS
FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS`
WHERE 1=1
    AND SIT_SITE_ID = 'MLB'
    AND CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-11-30'
    AND PROCESS_NAME = 'Ventas y Publicaciones'
    AND FLAG_EXCLUDE_NUMERATOR_CR = 0
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 20
