-- Muestrear 30 conversaciones de Bugs por período
WITH CASOS_BUGS AS (
    SELECT 
        C.CAS_CASE_ID,
        C.CDU,
        DATE_TRUNC(C.CONTACT_DATE_ID, MONTH) AS PERIODO,
        C.CONTACT_DATE_ID,
        ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC(C.CONTACT_DATE_ID, MONTH) ORDER BY RAND()) AS rn
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    WHERE 1=1
        AND C.SIT_SITE_ID = 'MLB'
        AND C.CONTACT_DATE_ID BETWEEN '2025-11-01' AND '2025-12-31'
        AND C.PROCESS_NAME LIKE '%Ventas y Publicaciones%'
        AND C.CDU = 'Bugs'
        AND C.PROCESS_BU_CR_REPORTING IN ('ME','ML')
        AND COALESCE(C.FLAG_EXCLUDE_NUMERATOR_CR, 0) = 0
        AND C.SIT_SITE_ID NOT IN ('MLV')
        AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND C.PROCESS_ID NOT IN (1312)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
)
SELECT 
    CB.CAS_CASE_ID,
    CB.CDU,
    CB.PERIODO,
    CB.CONTACT_DATE_ID,
    TRIM(REGEXP_REPLACE(
        CONCAT(
            COALESCE(JSON_VALUE(S.SUMMARY_CX_STUDIO, '$.problem'), ''), 
            ' ', 
            COALESCE(JSON_VALUE(S.SUMMARY_CX_STUDIO, '$.solution'), '')
        ), 
        r'\\s+', ' '
    )) AS CONVERSATION_SUMMARY
FROM CASOS_BUGS CB
INNER JOIN `meli-bi-data.WHOWNER.BT_CX_STUDIO_SAMPLE` S
    ON CB.CAS_CASE_ID = S.CAS_CASE_ID
WHERE CB.rn <= 30
ORDER BY CB.PERIODO, CB.CONTACT_DATE_ID
