WITH CLASIFICACION AS (
    SELECT
        C.CAS_CASE_ID,
        CAST(C.CONTACT_DATE_ID AS DATE) AS CONTACT_DATE,
        DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), WEEK(MONDAY)) AS SEMANA,
        CASE
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Mercado Env%'
                 AND C.PROCESS_GROUP_ECOMMERCE IN ('Vendedor') THEN 'ME PreDespacho'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE 'Post Compra Funcionalidades Vendedor'
                 AND C.PROCESS_BU_CR_REPORTING IN ('ME') THEN 'ME PreDespacho'
            ELSE 'OTRO'
        END AS AGRUP_COMMERCE
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    WHERE
        CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-09-01' AND '2026-01-31'
        AND C.SIT_SITE_ID = 'MLB'
        AND C.PROCESS_ID NOT IN (1312)
        AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
        AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
        AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
),
WEEKLY_INCOMING AS (
    SELECT
        SEMANA,
        COUNT(DISTINCT CAS_CASE_ID) AS INCOMING
    FROM CLASIFICACION
    WHERE AGRUP_COMMERCE = 'ME PreDespacho'
    GROUP BY 1
),
WEEKLY_DRIVER AS (
    SELECT
        DATE_TRUNC(drv.MONTH_ID, WEEK(MONDAY)) AS SEMANA,
        SUM(drv.OS_WITHOUT_FBM) / 4.33 AS DRIVER_SEMANAL
    FROM `meli-bi-data.WHOWNER.BT_CX_DRIVERS_CR` drv
    WHERE drv.MONTH_ID BETWEEN '2025-09-01' AND '2026-01-31'
    GROUP BY 1
)
SELECT
    w.SEMANA,
    w.INCOMING,
    COALESCE(d.DRIVER_SEMANAL, 0) AS DRIVER_SEMANAL,
    CASE WHEN d.DRIVER_SEMANAL > 0
        THEN (w.INCOMING / d.DRIVER_SEMANAL) * 100
        ELSE 0
    END AS CR_SEMANAL
FROM WEEKLY_INCOMING w
LEFT JOIN WEEKLY_DRIVER d ON w.SEMANA = d.SEMANA
ORDER BY w.SEMANA
