-- FASE 1: Incoming PNR MLU - Nov vs Dic 2025
-- Baseline: Incoming mensual con clasificación CASE WHEN oficial

WITH classified AS (
  SELECT 
    C.CAS_CASE_ID,
    DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), MONTH) AS MES,
    CASE
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PDD%') THEN 'PDD'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Others' THEN 'PDD'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PNR%') THEN 'PNR'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Others%') THEN 'PDD'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Mercado Envíos%') AND C.PROCESS_GROUP_ECOMMERCE IN ('Comprador') THEN 'ME Distribución'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Mercado Envíos%') AND C.PROCESS_GROUP_ECOMMERCE IN ('Vendedor') THEN 'ME PreDespacho'
      WHEN C.PROCESS_GROUP_ECOMMERCE IN ('Driver', 'Drivers') THEN 'ME Drivers'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%FBM Sellers%') THEN 'FBM Sellers'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PreVenta%') THEN 'Pre Venta'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PostVenta%') THEN 'Post Venta'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Prustomer%') THEN 'Moderaciones'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Post Compra%') AND C.PROCESS_GROUP_ECOMMERCE IN ('Comprador') THEN 'PCF Comprador'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Post Compra%') AND C.PROCESS_GROUP_ECOMMERCE IN ('Vendedor') THEN 'PCF Vendedor'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Compra%') THEN 'Generales Compra'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Pagos%') THEN 'Pagos'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%MP Payer%') THEN 'MP On'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%MP On%') THEN 'MP On'
      ELSE 'OTRO'
    END AS AGRUP_COMMERCE
  FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
  WHERE CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-11-01' AND '2025-12-31'
    AND C.SIT_SITE_ID = 'MLU'
    AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
    AND C.PROCESS_ID NOT IN (1312)
    AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
    AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
    AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
)
SELECT 
  MES,
  COUNT(DISTINCT CAS_CASE_ID) AS INCOMING
FROM classified
WHERE AGRUP_COMMERCE = 'PNR'
GROUP BY 1
ORDER BY 1
