-- FASE 1: Driver PNR MLU - Nov vs Dic 2025
-- PNR = Post-Compra → Driver: Órdenes GLOBALES (sin filtro site)

SELECT 
  DATE_TRUNC(ORD.ORD_CLOSED_DT, MONTH) AS MES,
  COUNT(DISTINCT ORD.ORD_ORDER_ID) AS DRIVER
FROM `meli-bi-data.WHOWNER.BT_ORD_ORDERS` ORD
WHERE ORD.ORD_CLOSED_DT BETWEEN '2025-11-01' AND '2025-12-31'
  AND ORD.ORD_GMV_FLG = TRUE
  AND ORD.ORD_MARKETPLACE_FLG = TRUE
  AND ORD.SIT_SITE_ID NOT IN ('MLV')
  AND (UPPER(ORD.DOM_DOMAIN_ID) <> 'TIPS')
GROUP BY 1
ORDER BY 1
