WITH CLASIFICACION AS (
    SELECT
        C.CAS_CASE_ID,
        DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), MONTH) AS FECHA_MONTH,
        C.PROCESS_NAME,
        C.CDU,
        CASE
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%PDD%' THEN 'PDD'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Others' THEN 'PDD'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%PNR%' THEN 'PNR'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Others%' THEN 'PDD'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Mercado Env%'
                 AND C.PROCESS_GROUP_ECOMMERCE IN ('Comprador') THEN 'ME Distribucion'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Post Compra Comprador%'
                 AND C.PROCESS_BU_CR_REPORTING IN ('ME') THEN 'ME Distribucion'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Mercado Env%'
                 AND C.PROCESS_GROUP_ECOMMERCE IN ('Vendedor') THEN 'ME PreDespacho'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE 'Post Compra Funcionalidades Vendedor'
                 AND C.PROCESS_BU_CR_REPORTING IN ('ME') THEN 'ME PreDespacho'
            WHEN C.PROCESS_GROUP_ECOMMERCE IN ('Driver', 'Drivers', 'Drivers y Places') THEN 'ME Drivers'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%FBM Sellers%' THEN 'FBM Sellers'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%PreVenta%' THEN 'Pre Venta'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%PostVenta%' THEN 'Post Venta'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Redes%' THEN 'Generales Compra'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Prustomer%' THEN 'Moderaciones'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Post Compra%' THEN 'Generales Compra'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Compra%' THEN 'Generales Compra'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Pagos%' THEN 'Pagos'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%MP Payer%' THEN 'MP On'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%MP On%' THEN 'MP On'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Seguridad 360%' THEN 'Cuenta'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Experiencia Impositiva%' THEN 'Experiencia Impositiva'
            ELSE 'Generales Compra'
        END AS AGRUP_COMMERCE
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    WHERE
        CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-12-01' AND '2026-01-31'
        AND C.SIT_SITE_ID = 'MLB'
        AND C.PROCESS_ID NOT IN (1312)
        AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
        AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
        AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
)
SELECT
    FECHA_MONTH,
    PROCESS_NAME,
    COUNT(DISTINCT CAS_CASE_ID) AS INCOMING
FROM CLASIFICACION
WHERE AGRUP_COMMERCE = 'ME PreDespacho'
GROUP BY 1, 2
ORDER BY 1, INCOMING DESC
