-- Gráfico Semanal: PNR MLU - 14+ semanas (Sep 2025 - Dic 2025)
-- Contexto de 4 meses para Chart.js

WITH classified AS (
  SELECT 
    C.CAS_CASE_ID,
    CAST(C.CONTACT_DATE_ID AS DATE) AS CONTACT_DATE,
    DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), ISOWEEK) AS SEMANA,
    CASE
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PDD%') THEN 'PDD'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Others' THEN 'PDD'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PNR%') THEN 'PNR'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%Others%') THEN 'PDD'
      ELSE 'OTRO'
    END AS AGRUP_COMMERCE
  FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
  WHERE CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-09-01' AND '2025-12-31'
    AND C.SIT_SITE_ID = 'MLU'
    AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
    AND C.PROCESS_ID NOT IN (1312)
    AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
    AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
    AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
),
weekly_incoming AS (
  SELECT 
    SEMANA,
    COUNT(DISTINCT CAS_CASE_ID) AS INCOMING
  FROM classified
  WHERE AGRUP_COMMERCE = 'PNR'
  GROUP BY 1
),
weekly_driver AS (
  SELECT 
    DATE_TRUNC(ORD.ORD_CLOSED_DT, ISOWEEK) AS SEMANA,
    COUNT(DISTINCT ORD.ORD_ORDER_ID) AS DRIVER
  FROM `meli-bi-data.WHOWNER.BT_ORD_ORDERS` ORD
  WHERE ORD.ORD_CLOSED_DT BETWEEN '2025-09-01' AND '2025-12-31'
    AND ORD.ORD_GMV_FLG = TRUE
    AND ORD.ORD_MARKETPLACE_FLG = TRUE
    AND ORD.SIT_SITE_ID NOT IN ('MLV')
    AND (UPPER(ORD.DOM_DOMAIN_ID) <> 'TIPS')
  GROUP BY 1
)
SELECT 
  wi.SEMANA,
  wi.INCOMING,
  wd.DRIVER,
  ROUND((wi.INCOMING / wd.DRIVER) * 100, 4) AS CR
FROM weekly_incoming wi
LEFT JOIN weekly_driver wd ON wi.SEMANA = wd.SEMANA
WHERE wd.DRIVER > 0
ORDER BY wi.SEMANA
