-- Diagnóstico: Ver qué PROCESS_PROBLEMATIC_REPORTING + PROCESS_GROUP_ECOMMERCE existe para MLB ME
SELECT 
    C.PROCESS_PROBLEMATIC_REPORTING,
    C.PROCESS_GROUP_ECOMMERCE,
    C.PROCESS_BU_CR_REPORTING,
    DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), MONTH) AS FECHA_MONTH,
    COUNT(DISTINCT C.CAS_CASE_ID) AS CASOS
FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
WHERE
    CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-12-01' AND '2026-01-31'
    AND C.SIT_SITE_ID = 'MLB'
    AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
    AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
    AND (
        C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Mercado Env%'
        OR C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Post Compra%'
        OR C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Envío%'
        OR C.PROCESS_PROBLEMATIC_REPORTING LIKE '%envio%'
        OR C.PROCESS_PROBLEMATIC_REPORTING LIKE '%ME %'
        OR C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Redes%'
        OR C.PROCESS_PROBLEMATIC_REPORTING LIKE '%CAP%'
    )
GROUP BY 1, 2, 3, 4
ORDER BY CASOS DESC
LIMIT 50
