-- FASE 3: Peak Detection - PNR MLU - Dic 2025
-- CR subió → buscar peaks en P2 (Diciembre)
-- Por ENVIRONMENT priorizado (MP_ON, FLEX)

WITH classified AS (
  SELECT 
    C.CAS_CASE_ID,
    CAST(C.CONTACT_DATE_ID AS DATE) AS FECHA,
    COALESCE(C.ENVIRONMENT, '(sin environment)') AS ENVIRONMENT,
    CASE
      WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PNR%') THEN 'PNR'
      WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
      ELSE 'OTRO'
    END AS AGRUP_COMMERCE
  FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
  WHERE CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-12-01' AND '2025-12-31'
    AND C.SIT_SITE_ID = 'MLU'
    AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
    AND C.PROCESS_ID NOT IN (1312)
    AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
    AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
    AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
),
diario AS (
  SELECT 
    ENVIRONMENT,
    FECHA,
    COUNT(DISTINCT CAS_CASE_ID) AS CASOS
  FROM classified
  WHERE AGRUP_COMMERCE = 'PNR'
    AND ENVIRONMENT IN ('MP_ON', 'FLEX')
  GROUP BY 1, 2
),
stats AS (
  SELECT 
    ENVIRONMENT,
    AVG(CASOS) AS PROMEDIO,
    STDDEV(CASOS) AS DESV_STD
  FROM diario
  GROUP BY 1
)
SELECT 
  d.ENVIRONMENT,
  d.FECHA,
  d.CASOS,
  ROUND(s.PROMEDIO, 1) AS PROMEDIO,
  ROUND(s.DESV_STD, 1) AS DESV_STD,
  ROUND(s.PROMEDIO + 1.5 * s.DESV_STD, 1) AS UMBRAL_PICO,
  CASE 
    WHEN d.CASOS > (s.PROMEDIO + 1.5 * s.DESV_STD) THEN 'PICO'
    ELSE 'NORMAL'
  END AS CLASIFICACION
FROM diario d
JOIN stats s ON d.ENVIRONMENT = s.ENVIRONMENT
ORDER BY d.ENVIRONMENT, d.FECHA
