WITH CLASIFICACION AS (
    SELECT
        C.CAS_CASE_ID,
        DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), MONTH) AS FECHA_MONTH,
        C.PROCESS_NAME,
        C.CDU,
        CASE
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%PDD%' THEN 'PDD'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Others' THEN 'PDD'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%PNR%' THEN 'PNR'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Others%' THEN 'PDD'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Mercado Env%'
                 AND C.PROCESS_GROUP_ECOMMERCE IN ('Comprador') THEN 'ME Distribucion'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Post Compra Comprador%'
                 AND C.PROCESS_BU_CR_REPORTING IN ('ME') THEN 'ME Distribucion'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%Mercado Env%'
                 AND C.PROCESS_GROUP_ECOMMERCE IN ('Vendedor') THEN 'ME PreDespacho'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE 'Post Compra Funcionalidades Vendedor'
                 AND C.PROCESS_BU_CR_REPORTING IN ('ME') THEN 'ME PreDespacho'
            WHEN C.PROCESS_GROUP_ECOMMERCE IN ('Driver', 'Drivers', 'Drivers y Places') THEN 'ME Drivers'
            WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE '%FBM Sellers%' THEN 'FBM Sellers'
            ELSE 'OTRO'
        END AS AGRUP_COMMERCE
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    WHERE
        CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-12-01' AND '2026-01-31'
        AND C.SIT_SITE_ID = 'MLB'
        AND C.PROCESS_ID NOT IN (1312)
        AND C.PROCESS_BU_CR_REPORTING IN ('ME', 'ML')
        AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
        AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
)
SELECT
    CDU,
    SUM(CASE WHEN FECHA_MONTH = '2025-12-01' THEN 1 ELSE 0 END) AS INC_P1,
    SUM(CASE WHEN FECHA_MONTH = '2026-01-01' THEN 1 ELSE 0 END) AS INC_P2,
    SUM(CASE WHEN FECHA_MONTH = '2026-01-01' THEN 1 ELSE 0 END) -
    SUM(CASE WHEN FECHA_MONTH = '2025-12-01' THEN 1 ELSE 0 END) AS VAR_CASOS
FROM CLASIFICACION
WHERE AGRUP_COMMERCE = 'ME PreDespacho'
GROUP BY 1
ORDER BY ABS(SUM(CASE WHEN FECHA_MONTH = '2026-01-01' THEN 1 ELSE 0 END) -
         SUM(CASE WHEN FECHA_MONTH = '2025-12-01' THEN 1 ELSE 0 END)) DESC
