-- FASE 3: Muestreo Unificado - PNR MLU - Nov vs Dic 2025
-- Environments priorizados: MP_ON (80.7%), FLEX (11.2%)
-- Join: BT_CX_CONTACTS + BT_CX_STUDIO_SAMPLE

WITH STUDIO_SUMMARIES AS (
    SELECT
        CAS_CASE_ID,
        TRIM(REGEXP_REPLACE(
            CONCAT(
                COALESCE(JSON_VALUE(SUMMARY_CX_STUDIO, '$.problem'), ''),
                ' ',
                COALESCE(JSON_VALUE(SUMMARY_CX_STUDIO, '$.solution'), '')
            ),
            r'\s+', ' '
        )) AS CONVERSATION_SUMMARY
    FROM `meli-bi-data.WHOWNER.BT_CX_STUDIO_SAMPLE`
    WHERE ARRIVAL_DATE BETWEEN DATE_SUB(DATE '2025-11-01', INTERVAL 30 DAY) 
        AND DATE_ADD(DATE '2025-12-31', INTERVAL 30 DAY)
),

INCOMING_BASE AS (
    SELECT
        C.CAS_CASE_ID,
        COALESCE(C.ENVIRONMENT, '(sin environment)') AS ENVIRONMENT,
        DATE(C.CONTACT_DATE_ID) AS FECHA_CONTACTO,
        DATE_TRUNC(CAST(C.CONTACT_DATE_ID AS DATE), MONTH) AS MES,
        CASE
          WHEN C.PROCESS_PROBLEMATIC_REPORTING LIKE ('%PNR%') THEN 'PNR'
          WHEN C.PROCESS_PROBLEMATIC_REPORTING = 'Conflict Stale' THEN 'PNR'
          ELSE 'OTRO'
        END AS AGRUP_COMMERCE
    FROM `meli-bi-data.WHOWNER.BT_CX_CONTACTS` C
    WHERE C.SIT_SITE_ID = 'MLU'
        AND CAST(C.CONTACT_DATE_ID AS DATE) BETWEEN '2025-11-01' AND '2025-12-31'
        AND C.PROCESS_BU_CR_REPORTING IN ('ME','ML')
        AND C.FLAG_EXCLUDE_NUMERATOR_CR = 0
        AND C.PROCESS_ID NOT IN (1312)
        AND C.QUEUE_ID NOT IN (2131, 230, 1102, 1241, 2075, 2294, 2295)
        AND COALESCE(C.CI_REASON_ID, 0) NOT IN (2592, 6588, 10068, 2701, 10048)
        AND C.ENVIRONMENT IN ('MP_ON', 'FLEX')
),

JOINED AS (
    SELECT 
        INC.CAS_CASE_ID,
        INC.ENVIRONMENT,
        INC.FECHA_CONTACTO,
        INC.MES,
        CASE WHEN INC.MES = '2025-11-01' THEN 'P1' ELSE 'P2' END AS PERIODO,
        ST.CONVERSATION_SUMMARY
    FROM INCOMING_BASE INC
    INNER JOIN STUDIO_SUMMARIES ST ON INC.CAS_CASE_ID = ST.CAS_CASE_ID
    WHERE INC.AGRUP_COMMERCE = 'PNR'
        AND ST.CONVERSATION_SUMMARY IS NOT NULL
        AND LENGTH(ST.CONVERSATION_SUMMARY) > 20
),

WITH_TIPO AS (
    SELECT 
        *,
        CASE 
            -- Peaks P2 Dic: MP_ON 16,23 | FLEX 3,23,30
            WHEN PERIODO = 'P2' AND ENVIRONMENT = 'MP_ON' AND FECHA_CONTACTO IN ('2025-12-16', '2025-12-23') THEN 'PICO'
            WHEN PERIODO = 'P2' AND ENVIRONMENT = 'FLEX' AND FECHA_CONTACTO IN ('2025-12-03', '2025-12-23', '2025-12-30') THEN 'PICO'
            ELSE 'NORMAL'
        END AS TIPO_DIA
    FROM JOINED
),

RANKED AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (
            PARTITION BY ENVIRONMENT, PERIODO, TIPO_DIA 
            ORDER BY RAND()
        ) AS RN
    FROM WITH_TIPO
)

SELECT 
    CAS_CASE_ID,
    FECHA_CONTACTO,
    ENVIRONMENT,
    PERIODO,
    TIPO_DIA,
    CONVERSATION_SUMMARY
FROM RANKED
WHERE 
    -- P2: 21 picos + 9 normales por env
    (PERIODO = 'P2' AND TIPO_DIA = 'PICO' AND RN <= 21)
    OR (PERIODO = 'P2' AND TIPO_DIA = 'NORMAL' AND RN <= 9)
    -- P1: 30 aleatorios por env (todos NORMAL)
    OR (PERIODO = 'P1' AND RN <= 30)
ORDER BY ENVIRONMENT, PERIODO, FECHA_CONTACTO
